title: Karthikeyan Sivakumar
logo: /assets/img/my-profile.JPG
description: Software Engineer | AI/ML Engineer | Contact: karthikeyan@example.com | Phone: +1 234 567 8901
show_downloads: false
theme: jekyll-theme-minimal


