title: Karthikeyan Sivakumar
logo: /assets/img/My-Git-Profile.JPG
Description:  MS Computer Science & AI | AI/ML Engineer | Microsoft Certified Data Scientist and AI Engineer. 
show_downloads: false
theme: jekyll-theme-minimal
