title: Karthikeyan Sivakumar
logo: /assets/img/my-profile.JPG
Description: I am an optimistic master's in CS & AI graduate with 3 and half years of experience as a software engineer and AI/ML engineer. I hold Microsoft Certified Data Scientist and AI Engineer credentials and have solid technical skills and proficiency in Python.  
show_downloads: false
theme: jekyll-theme-minimal

  


