title: Karthikeyan Sivakumar
logo: /assets/img/my-profile.JPG
description: MS Computer Science & AI | AI/ML Engineer 
email: karthinottsuk@gmail.com
show_downloads: false
theme: jekyll-theme-minimal

  


