title: Karthikeyan Sivakumar
logo: /assets/img/headshot_circle.png
description: Software Engineer | AI/ML Engineer
theme: jekyll-theme-minimal


specialisation: Data Science, AI/ML, MLOps
microsft Certified: Data Scientist and AI Engineer

# Additional Information
email: karthinottsuk@gmail.com
linkedIn: https://www.linkedin.com/in/karthi-linkedin
contact: +44 77679 76623

# Add language logo
